
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/HeaderPage";
import AuthSessionProvider from "@/components/SessionProvider";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthSessionProvider>
          <HeaderPage />
          <main className="flex-1">
            {children}
          </main>
        </AuthSessionProvider>
        <Footer />
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
